repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/hadialqattan/pycln
    rev: v2.4.0
    hooks:
      - id: pycln
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.12.1
    hooks:
      - id: mypy
        args: [--show-error-codes]
        additional_dependencies: [types-dataclasses]

  # - repo: https://github.com/pre-commit/mirrors-autopep8
  #   rev: 'v1.5.7'
  #   hooks:
  #   - id: autopep8

  - repo: https://github.com/psf/black
    rev: '24.10.0'
    hooks:
    - id: black
