#!/usr/bin/env bash

# echo "~/.dot/macrc: mac settings settings"

export APPLICATION_DIR="${HOME}/Applications"
export HOMEBREW_HOME="${APPLICATION_DIR}/brew"
export HOMEBREW_PREFIX="${HOMEBREW_HOME}"
export HOMEBREW_CASK_OPTS="--appdir=${APPLICATION_DIR}"

addToPath "${HOMEBREW_HOME}/bin"
addToPath "${DOT_HOME}/bin/darwin"

alias showhidden='defaults write com.apple.Finder AppleShowAllFiles true; killall Finder'
# alias jira='git symbolic-ref -q HEAD | rev | cut -d/ -f1 | rev | grep -oE "^[A-Z]{2,}-[0-9]+" | xargs -I {} open "https://jira.com/jira/browse/{}"'
# alias repo='git remote -v | grep -m 1 -oE "github.com.*.git" | tr ":" "/" | xargs -I {} open "https://{}"'
# alias pr='open "https://$(git remote -v | grep -m 1 -oE "github.com:[A-Za-z\-]+/[A-Za-z\-]+" | tr ":" "/")/pull/new/$(git branch | grep "*" | cut -d " " -f2)"'

# export NVM_DIR="${HOME}/.nvm"
# [ -s "${HOMEBREW_HOME}/opt/nvm/nvm.sh" ] &&
#     . "${HOMEBREW_HOME}/opt/nvm/nvm.sh" # This loads nvm
# [ -s "${HOMEBREW_HOME}/opt/nvm/etc/bash_completion.d/nvm" ] &&
#     . "${HOMEBREW_HOME}/opt/nvm/etc/bash_completion.d/nvm" # This loads nvm bash_completion
