#!/usr/bin/env bash

echo "~/.dot/dotrc: common settings"
export PATH="$HOME/.local/bin:$PATH"

export CLICOLOR=1
export LSCOLORS=GxFxCxDxBxegedabagaced

export WORKON_HOME="${HOME}/.virtualenvs"
export VIRTUALENVWRAPPER_PYTHON=$(which python3 || which python)
export PYTHONUSERBASE="${HOME}/.local"
# export PIP_INDEX_URL="http://www.example.com/my-packages/"
export PIPENV_VENV_IN_PROJECT=1

alias dot='git "--git-dir=${HOME}/.cfg/" "--work-tree=${HOME}"'
command -v code-insiders >/dev/null 2>&1 &&
     alias code="code-insiders"

[ -f "${HOME}/.local/bin/virtualenvwrapper_lazy.sh" ] &&
     source "${HOME}/.local/bin/virtualenvwrapper_lazy.sh"

################################################################################
uname -s | grep -q Darwin && source "${HOME}/.dot/macrc"
uname -s | grep -q Linux && source "${HOME}/.dot/linuxrc"
[ -f "${HOME}/.dotrc" ] && source "${HOME}/.dotrc"
