#!/usr/bin/env bash
# shellcheck source=/dev/null

echo "~/.dot/linuxrc: linux settings"

export PATH="${HOME}/.dot/linux_bin:${PATH}"

command -v javac >/dev/null 2>&1 &&
  JAVA_HOME=$(dirname "$(dirname "$(readlink -f "$(command -v javac)")")") &&
  export JAVA_HOME
