#!/usr/bin/env bash

echo "~/.dot/linuxrc: linux settings"

export PATH="${HOME}/.dot/linux_bin:${PATH}"

command -v javac >/dev/null 2>&1 &&
    export JAVA_HOME=$(dirname "$(dirname "$(readlink -f "$(command -v javac)")")")
