#!/usr/bin/env bash

echo "~/.dot/macrc: mac settings settings"

export APPLICATION_DIR="${HOME}/Applications"
export HOMEBREW_HOME="${APPLICATION_DIR}/brew"
export HOMEBREW_PREFIX="${HOMEBREW_HOME}"
export HOMEBREW_CASK_OPTS="--appdir=${APPLICATION_DIR}"
export PATH="${HOMEBREW_HOME}/bin:${PATH}"
export PATH="${HOME}/.dot/mac_bin:${PATH}"

[ -f /usr/libexec/java_home ] 2>&1 &&
    export JAVA_HOME="$(/usr/libexec/java_home)"

export NVM_DIR="${HOME}/.nvm"
[ -s "${HOMEBREW_HOME}/opt/nvm/nvm.sh" ] &&
    . "${HOMEBREW_HOME}/opt/nvm/nvm.sh" # This loads nvm
[ -s "${HOMEBREW_HOME}/opt/nvm/etc/bash_completion.d/nvm" ] &&
    . "${HOMEBREW_HOME}/opt/nvm/etc/bash_completion.d/nvm" # This loads nvm bash_completion
